name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bgcodehub
          template: classic
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming, markup, prose
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14